### PR TITLE
Cleanup option for make_manifest.py

### PR DESCRIPTION
**Pull request by IevgeniiB**
@pprett please, take a look at this option. As was said in function description, it just removes stale records from manifest.json

### CODE REVIEW

**Comment by pprett** [comment]
looks good @IevgeniiB +1 for a test

**Comment by IevgeniiB** [comment]
@pprett added tests

**Comment by pprett** [comment]
LGTM :+1: for merge

**Comment by IevgeniiB** [comment]
image
@pprett let's do it! :)

**Comment by pprett** [comment]
thanks @IevgeniiB

**Pull request merged**
